application_base_contests:
    path:     contests/
    defaults: { _controller: ApplicationBaseBundle:Default:contests }

application_base_prizes:
    path:     prizes/
    defaults: { _controller: ApplicationBaseBundle:Default:prizes }

application_base_catalog_products:
    path:     catalog-products/
    defaults: { _controller: ApplicationBaseBundle:Default:catalogProducts }