application_base_contests:
    path:     contests/
    defaults: { _controller: ApplicationBaseBundle:Default:contests }

application_base_contests_response_member:
    path:     contests/response-member/
    defaults: { _controller: ApplicationBaseBundle:Default:responseMemberContests }

application_base_prizes:
    path:     prizes/
    defaults: { _controller: ApplicationBaseBundle:Default:prizes }

application_base_catalog_products:
    path:     catalog-products/
    defaults: { _controller: ApplicationBaseBundle:Default:catalogProducts }

application_base_security_login_fb:
    path:     auth/login-fb/
    defaults: { _controller: ApplicationBaseBundle:Security:loginFb }

application_base_security_login_vk:
    path:     auth/login-vk/
    defaults: { _controller: ApplicationBaseBundle:Security:loginVk }

application_base_security_login_ok:
    path:     auth/login-ok/
    defaults: { _controller: ApplicationBaseBundle:Security:loginOk }