services:
    templates.statuses_manager:
        class: TemplatesBundle\Manager\StatusesManager
        arguments:
            em: '@doctrine.orm.entity_manager'
            container: '@service_container'
