application_admin_home:
    path:     /
    defaults: { _controller: ApplicationAdminBundle:Default:index }

application_admin_templates:
    path:     /templates/
    defaults: { _controller: ApplicationAdminBundle:Templates:index }

application_admin_templates_change_main_slider:
    path:     /templates/changr-main-slider/{id}/
    defaults: { _controller: ApplicationAdminBundle:Templates:changeMainSlider }

application_admin_checks:
    path:     /checks/
    defaults: { _controller: ApplicationAdminBundle:Checks:index }

application_admin_contests:
    path:     /contests/
    defaults: { _controller: ApplicationAdminBundle:Contests:index }
