application_admin_home:
    path:     /
    defaults: { _controller: ApplicationAdminBundle:Default:index }

application_admin_templates:
    path:     /templates/
    defaults: { _controller: ApplicationAdminBundle:Templates:index }

application_admin_templates_change_main_slider:
    path:     /templates/change-main-slider/{id}/
    defaults: { _controller: ApplicationAdminBundle:Templates:changeMainSlider }

application_admin_templates_change_main_tip:
    path:     /templates/change-main-tip/{id}/
    defaults: { _controller: ApplicationAdminBundle:Templates:changeMainTip }

application_admin_checks:
    path:     /checks/
    defaults: { _controller: ApplicationAdminBundle:Checks:index }

application_admin_checks_approved:
    path:     /checks/approved/{id}/
    defaults: { _controller: ApplicationAdminBundle:Checks:approvedCheck }

application_admin_checks_disallow:
    path:     /checks/disallow/{id}/
    defaults: { _controller: ApplicationAdminBundle:Checks:disallowCheck }

application_admin_contests:
    path:     /contests/
    defaults: { _controller: ApplicationAdminBundle:Contests:index }

application_admin_contests_edit:
    path:     /contests/edit/{id}
    defaults: { _controller: ApplicationAdminBundle:Contests:editContest, id: null }

application_admin_contests_members:
    path:     /contests/members/{id}/
    defaults: { _controller: ApplicationAdminBundle:Contests:members }

application_admin_contests_member_more:
    path:     /contests/member-more/{id}/
    defaults: { _controller: ApplicationAdminBundle:Contests:memberMore }

application_admin_contests_member_approved:
    path:     /contests/member-approved/{id}/
    defaults: { _controller: ApplicationAdminBundle:Contests:approvedMemberResponse }

application_admin_contests_member_disallow:
    path:     /contests/member-disallow/{id}/
    defaults: { _controller: ApplicationAdminBundle:Contests:disallowMemberResponse }

application_admin_prizes:
    path:     /prizes/
    defaults: { _controller: ApplicationAdminBundle:Prizes:index }

application_admin_prizes_edit:
    path:     /prizes/edit/{id}
    defaults: { _controller: ApplicationAdminBundle:Prizes:editPrize, id: null }

application_admin_statuses:
    path:     /statuses/
    defaults: { _controller: ApplicationAdminBundle:Statuses:index }

application_admin_statuses_edit:
    path:     /statuses/edit/{name}
    defaults: { _controller: ApplicationAdminBundle:Statuses:editStatus }

application_admin_statuses_edit_table_scores:
    path:     /statuses/edit-table-scores/{type}
    defaults: { _controller: ApplicationAdminBundle:Statuses:editTableScores }

application_admin_reviews:
    path:     /reviews/
    defaults: { _controller: ApplicationAdminBundle:Reviews:index }

application_admin_reviews_more:
    path:     /reviews/comment-more/{id}
    defaults: { _controller: ApplicationAdminBundle:Reviews:commentMore }

application_admin_reviews_approved:
    path:     /reviews/approved/{id}/
    defaults: { _controller: ApplicationAdminBundle:Reviews:approvedComment }

application_admin_reviews_disallow:
    path:     /reviews/disallow/{id}/
    defaults: { _controller: ApplicationAdminBundle:Reviews:disallowComment }

application_admin_testing:
    path:     /testing/
    defaults: { _controller: ApplicationAdminBundle:Testing:index }

application_admin_testing_customer_info_more:
    path:     /testing/customer-info-more/{id}/
    defaults: { _controller: ApplicationAdminBundle:Testing:customerInfoMore }

application_admin_testing_approved_request:
    path:     /testing/approved-request/{id}/
    defaults: { _controller: ApplicationAdminBundle:Testing:approvedRequestTest }

application_admin_testing_disallow_request:
    path:     /testing/disallow-request/{id}/
    defaults: { _controller: ApplicationAdminBundle:Testing:disallowRequestTest }
