Application\AdminBundle\Entity\Prizes:
    properties:
        title:
            - NotBlank: {  message: property.blank }
        type:
            - NotBlank: {  message: property.option }
        file:
            - Image:
                mimeTypes:  [image/jpeg, image/pjpeg, image/png]
                minWidth: 230
                minWidthMessage: property.img_size.min_width_fix
                maxWidth: 230
                maxWidthMessage: property.img_size.max_width_fix
                minHeight: 284
                minHeightMessage: property.img_size.min_height_fix
                maxHeight: 284
                maxHeightMessage: property.img_size.max_height_fix


Application\AdminBundle\Entity\Contests:
    properties:
        title:
            - NotBlank: {  message: property.blank }
        description:
            - NotBlank: {  message: property.blank }
        file:
            - Image:
                mimeTypes:  [image/jpeg, image/pjpeg, image/png]
                minWidth: 231
                minWidthMessage: property.img_size.min_width_fix
                maxWidth: 231
                maxWidthMessage: property.img_size.max_width_fix
                minHeight: 290
                minHeightMessage: property.img_size.min_height_fix
                maxHeight: 290
                maxHeightMessage: property.img_size.max_height_fix
        startedAt:
            - Date: ~
            - NotBlank: {  message: property.blank }
        finishedAt:
            - Date: ~
            - NotBlank: {  message: property.blank }

