services:
    hg_product.shop_productions_manager:
        class: HgProductBundle\Manager\ShopProductions
        arguments:
            emHgProd: '@doctrine.orm.hg_prod_ru_entity_manager'



#    hg_product.example:
#        class: HgProductBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
