_home:
    pattern:  /
    defaults: { _controller: ApplicationBaseBundle:Default:index }

application_users:
    resource: "@ApplicationUsersBundle/Resources/config/routing.yml"
    prefix:   /

application_base:
    resource: "@ApplicationBaseBundle/Resources/config/routing.yml"
    prefix:   /

test_base:
    resource: "@TestBaseBundle/Resources/config/routing.yml"
    prefix:   /test

test_user:
    resource: "@TestUserBundle/Resources/config/routing.yml"
    prefix:   /users

test_message:
    resource: "@TestMessageBundle/Resources/config/routing.yml"
    prefix:   /message

app:
    resource: @AppBundle/Controller/
    type:     annotation
