application_test_production:
    resource: "@ApplicationTestProductionBundle/Resources/config/routing.yml"
    prefix:   /

# home page
_home:
    path:     /
    defaults: { _controller: ApplicationBaseBundle:Default:index }

# Login
application_base_security_login:
    path:     /login
    defaults: { _controller: ApplicationBaseBundle:Security:login }

application_base_security_login_check:
    path:     /login_check

# Logout
application_base_security_logout:
    path:     /logout


application_admin:
    resource: "@ApplicationAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

application_base:
    resource: "@ApplicationBaseBundle/Resources/config/routing.yml"
    prefix:   /

application_contests:
    resource: "@ApplicationContestsBundle/Resources/config/routing.yml"
    prefix:   /contests

application_message:
    resource: "@ApplicationMessageBundle/Resources/config/routing.yml"
    prefix:   /

application_prizes:
    resource: "@ApplicationPrizesBundle/Resources/config/routing.yml"
    prefix:   /

application_scores:
    resource: "@ApplicationScoresBundle/Resources/config/routing.yml"
    prefix:   /

application_users:
    resource: "@ApplicationUsersBundle/Resources/config/routing.yml"
    prefix:   /

hg_product:
    resource: "@HgProductBundle/Resources/config/routing.yml"
    prefix:   /hg-product

social_networks:
    resource: "@SocialNetworksBundle/Resources/config/routing.yml"
    prefix:   /social-networks

templates:
    resource: "@TemplatesBundle/Resources/config/routing.yml"
    prefix:   /

#fos_user_security:
#    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

