services:
    scores_action.service:
        class: Application\ScoresBundle\Service\ScoresActionService
        arguments: [@service_container]

    scores_table.service:
        class: Application\ScoresBundle\Service\ScoresTableService
        arguments:
            container: '@service_container'
            em: '@doctrine.orm.entity_manager'