Application\ScoresBundle\Entity\Scores:
    properties:
        points:
            - NotBlank: { message: property.blank }
            - Type:
                type: numeric
                message: property.number_only

