
Application\UsersBundle\Entity\Checks:
    properties:
        commentAdmin:
            - NotBlank: { message: property.blank, groups: [form-disallow] }
        points:
            - NotBlank: { message: property.blank, groups: [form-approved] }
            - Type:
                type: numeric
                message: property.number_only
                groups: [form-approved]

Application\UsersBundle\Entity\Users:
    properties:
        firstName:
            - NotBlank: { message: property.blank, groups: [edit-profile] }
            - Length:
                max: 30
                groups: [edit-profile]

        lastName:
            - NotBlank: { message: property.blank, groups: [edit-profile] }
            - Length:
                max: 30
                groups: [edit-profile]

        occupation:
            - Length:
                max: 60
                groups: [edit-profile]

        postcode:
            - Type:
                type: numeric
                message: property.number_only
                groups: [edit-profile]
            - Length:
                max: 6
                groups: [edit-profile]

        shippingAddress:
            - Length:
                max: 125
                groups: [edit-profile]

Application\UsersBundle\Entity\CommentsProduction:
    properties:
        nameProduct:
            - NotBlank: { message: property.blank }
        description:
            - NotBlank: { message: property.blank }
        commentAdmin:
            - NotBlank: { message: property.blank, groups: [form-disallow] }

