Application\PrizesBundle\Entity\Prizes:
    properties:
        title:
            - NotBlank: {  message: property.blank }
        type:
            - NotBlank: {  message: property.option }
        pointsBuy:
            - NotBlank: {  message: property.blank }
        file:
            - Image:
                mimeTypes:  [image/jpeg, image/pjpeg, image/png]
                minWidth: 228
                minWidthMessage: property.img_size.min_width_fix
                maxWidth: 228
                maxWidthMessage: property.img_size.max_width_fix
                minHeight: 306
                minHeightMessage: property.img_size.min_height_fix
                maxHeight: 306
                maxHeightMessage: property.img_size.max_height_fix
